CREATE DATABASE IF NOT EXISTS fastapp;
CREATE DATABASE IF NOT EXISTS testapp;

CREATE USER IF NOT EXISTS 'fastapi'@'%' IDENTIFIED BY 'fastapi123';

GRANT ALL PRIVILEGES ON fastapp.* TO 'fastapi'@'%';
GRANT ALL PRIVILEGES ON testapp.* TO 'fastapi'@'%';

FLUSH PRIVILEGES;
