CREATE DATABASE IF NOT EXISTS fastapp;
CREATE DATABASE IF NOT EXISTS testapp;
CREATE DATABASE IF NOT EXISTS paieapp;
CREATE USER IF NOT EXISTS 'fastapi'@'%' IDENTIFIED BY 'fastapi123';

GRANT ALL PRIVILEGES ON fastapp.* TO 'fastapi'@'%';
GRANT ALL PRIVILEGES ON testapp.* TO 'fastapi'@'%';
GRANT ALL PRIVILEGES ON paieapp.* TO 'fastapi'@'%';
FLUSH PRIVILEGES;
